version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: acme-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-acme}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-acme123}
      POSTGRES_DB: ${POSTGRES_DB:-acme_dev}
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-acme}']
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-test:
    image: postgres:16
    container_name: acme-postgres-test
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_TEST_USER:-acme}
      POSTGRES_PASSWORD: ${POSTGRES_TEST_PASSWORD:-acme123}
      POSTGRES_DB: ${POSTGRES_TEST_DB:-acme_test}
    ports:
      - '${POSTGRES_TEST_PORT:-5433}:5432'
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_TEST_USER:-acme}']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  postgres_test_data:
